# Generated by Django 5.2.1 on 2025-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
