# Generated by Django 5.2.1 on 2025-05-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_alter_item_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
