# Generated by Django 5.2.1 on 2025-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='return_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
